pub mod connect4;
pub mod connect4_computer;
pub mod game_history;
pub mod howToPlayConnect4;
pub mod howToPlayTooT;
pub mod mainPage;
pub mod score_board;
pub mod tootOtto;
pub mod tootOtto_computer;
